import { l } from "../data";
export const copy = {
  dashboard: l("Tableau de bord", "Dashboard", "لوحة التحكم"),
  overview: l("Vue d’ensemble", "Overview", "نظرة عامة"),
  menu: l("Carte & plats", "Menu & dishes", "القائمة والأطباق"),
  categories: l("Catégories", "Categories", "الفئات"),
  locations: l("Restaurants", "Locations", "الفروع"),
  reviews: l("Avis clients", "Customer reviews", "آراء الزبائن"),
  links: l("Réseaux & liens", "Social & links", "التواصل والروابط"),
  linksHelp: l(
    "Vos réseaux, vos liens de commande et les publications de la section « Suivez-nous » de la page d’accueil.",
    "Your social profiles, ordering links and the posts in the home page’s “Follow us” section.",
    "حساباتك، روابط الطلب ومنشورات قسم «تابعونا» في الصفحة الرئيسية.",
  ),
  socialLinks: l("Réseaux sociaux", "Social media", "مواقع التواصل"),
  socialLinksHelp: l(
    "Affichés dans la section « Suivez-nous » et en bas de page, dans cet ordre.",
    "Shown in the “Follow us” section and the footer, in this order.",
    "تظهر في قسم «تابعونا» وفي أسفل الصفحة، بهذا الترتيب.",
  ),
  orderLinks: l("Liens de commande", "Ordering links", "روابط الطلب"),
  orderLinksHelp: l(
    "Glovo reste le lien principal. Les autres s’affichent comme boutons « Commander sur … ».",
    "Glovo stays the main link. The others appear as “Order on …” buttons.",
    "غلوفو يبقى الرابط الرئيسي. الروابط الأخرى تظهر كأزرار «اطلب على …».",
  ),
  addSocial: l("Ajouter un réseau", "Add a social profile", "إضافة حساب"),
  addOrder: l(
    "Ajouter un lien de commande",
    "Add an ordering link",
    "إضافة رابط طلب",
  ),
  noLinks: l(
    "Aucun lien pour le moment.",
    "No links yet.",
    "لا توجد روابط بعد.",
  ),
  platform: l("Plateforme", "Platform", "المنصة"),
  otherPlatform: l("Autre…", "Other…", "أخرى…"),
  linkLabel: l("Nom affiché", "Display name", "الاسم المعروض"),
  linkUrl: l("Lien", "Link", "الرابط"),
  mainLink: l("Principal", "Main", "رئيسي"),
  glovoLinkHelp: l(
    "Obligatoire : utilisé par tous les boutons « Commander sur Glovo ».",
    "Required: used by every “Order on Glovo” button.",
    "إلزامي: يُستخدم في جميع أزرار «اطلب على غلوفو».",
  ),
  openLink: l("Ouvrir le lien", "Open link", "فتح الرابط"),
  moveUp: l("Monter", "Move up", "تحريك للأعلى"),
  moveDown: l("Descendre", "Move down", "تحريك للأسفل"),
  showOnSite: l(
    "Afficher sur le site",
    "Show on the website",
    "إظهار في الموقع",
  ),
  hideFromSite: l("Masquer du site", "Hide from the website", "إخفاء من الموقع"),
  unsaved: l(
    "Modifications non enregistrées",
    "Unsaved changes",
    "تغييرات غير محفوظة",
  ),
  discard: l("Annuler les modifications", "Discard changes", "تجاهل التغييرات"),
  posts: l("Publications & reels", "Posts & reels", "المنشورات والريلز"),
  postsHelp: l(
    "Collez le lien d’une publication ou d’un reel Instagram, Facebook ou TikTok. Ils défilent dans cet ordre dans la section « Suivez-nous ».",
    "Paste the link of an Instagram, Facebook or TikTok post or reel. They scroll in this order in the “Follow us” section.",
    "الصق رابط منشور أو ريل من Instagram أو Facebook أو TikTok. تظهر بهذا الترتيب في قسم «تابعونا».",
  ),
  postsEmpty: l(
    "Aucune publication : la section montre les photos du restaurant en attendant.",
    "No posts yet: the section shows the restaurant’s photos meanwhile.",
    "لا توجد منشورات: القسم يعرض صور المطعم في الوقت الحالي.",
  ),
  addPost: l("Ajouter une publication", "Add a post", "إضافة منشور"),
  postsLimit: l(
    "Limite de 4 publications atteinte.",
    "The 4-post limit is reached.",
    "تم بلوغ الحد الأقصى: 4 منشورات.",
  ),
  postUrl: l(
    "Lien de la publication ou du reel",
    "Post or reel link",
    "رابط المنشور أو الريل",
  ),
  postUrlInvalid: l(
    "Collez un lien Instagram, Facebook ou TikTok. Pour TikTok, utilisez le lien complet (…/video/…).",
    "Paste an Instagram, Facebook or TikTok link. For TikTok, use the full link (…/video/…).",
    "الصق رابط Instagram أو Facebook أو TikTok. بالنسبة لـ TikTok استعمل الرابط الكامل (…/video/…).",
  ),
  postCaption: l("Légende · facultatif", "Caption · optional", "التعليق · اختياري"),
  postMedia: l(
    "Vidéo et couverture · facultatif",
    "Video and cover · optional",
    "الفيديو والغلاف · اختياري",
  ),
  postMediaHelp: l(
    "Instagram et Facebook ne laissent pas un site régler le son de leur lecteur. Ajoutez le fichier vidéo du reel pour une lecture automatique en sourdine, avec bouton son. TikTok fonctionne avec le lien seul.",
    "Instagram and Facebook do not let a website control their player’s sound. Add the reel’s video file for muted autoplay with a sound button. TikTok works from the link alone.",
    "Instagram وFacebook لا يسمحان للموقع بالتحكم في صوت مشغلهما. أضف ملف فيديو الريل لتشغيل تلقائي بدون صوت مع زر للصوت. TikTok يعمل بالرابط فقط.",
  ),
  postVideo: l("Vidéo (MP4 ou WebM)", "Video (MP4 or WebM)", "فيديو (MP4 أو WebM)"),
  postPoster: l("Image de couverture", "Cover image", "صورة الغلاف"),
  uploadVideo: l("Téléverser une vidéo", "Upload a video", "رفع فيديو"),
  videoHelp: l(
    "MP4 ou WebM · 50 Mo maximum.",
    "MP4 or WebM · 50 MB maximum.",
    "MP4 أو WebM · 50 ميغابايت كحد أقصى.",
  ),
  videoType: l(
    "Format non pris en charge. Utilisez MP4 ou WebM.",
    "Unsupported format. Use MP4 or WebM.",
    "صيغة غير مدعومة. استخدم MP4 أو WebM.",
  ),
  videoSize: l(
    "Vidéo trop lourde. 50 Mo maximum.",
    "Video too large. 50 MB maximum.",
    "الفيديو كبير جداً. 50 ميغابايت كحد أقصى.",
  ),
  reel: l("Reel", "Reel", "ريل"),
  video: l("Vidéo", "Video", "فيديو"),
  post: l("Publication", "Post", "منشور"),
  playsMuted: l(
    "Lecture automatique en sourdine, avec bouton son",
    "Plays muted automatically, with a sound button",
    "تشغيل تلقائي بدون صوت، مع زر للصوت",
  ),
  playsEmbed: l(
    "Lecteur officiel : le visiteur lance la lecture",
    "Official player: visitors start playback",
    "المشغل الرسمي: الزائر يبدأ التشغيل",
  ),
  playsLink: l(
    "Carte avec lien (ajoutez une couverture)",
    "Link card (add a cover image)",
    "بطاقة برابط (أضف صورة غلاف)",
  ),
  reviewsHelp: l(
    "Vérifiez les avis et leurs photos avant publication. Seuls les avis approuvés apparaissent sur le site.",
    "Check reviews and photos before publishing. Only approved reviews appear on the website.",
    "راجع الآراء والصور قبل النشر. تظهر الآراء المعتمدة فقط على الموقع.",
  ),
  reviewsPending: l("En attente", "Pending", "قيد المراجعة"),
  reviewsApproved: l("Approuvés", "Approved", "معتمدة"),
  reviewsRejected: l("Refusés", "Rejected", "مرفوضة"),
  reviewsFilter: l("Filtrer les avis", "Filter reviews", "تصفية الآراء"),
  reviewsSearch: l("Rechercher un avis…", "Search reviews…", "البحث في الآراء…"),
  reviewsRefresh: l("Actualiser les avis", "Refresh reviews", "تحديث الآراء"),
  reviewsApprove: l("Approuver", "Approve", "اعتماد"),
  reviewsReject: l("Refuser", "Reject", "رفض"),
  reviewApproved: l("Avis approuvé et publié.", "Review approved and published.", "تم اعتماد الرأي ونشره."),
  reviewRejected: l("Avis refusé et masqué du site.", "Review rejected and hidden from the website.", "تم رفض الرأي وإخفاؤه من الموقع."),
  reviewsEmpty: l("Aucun avis dans cette sélection.", "No reviews in this selection.", "لا توجد آراء ضمن هذا الاختيار."),
  reviewsEmptyHelp: l("Les nouveaux avis arrivent ici en attente de votre décision.", "New reviews appear here while awaiting your decision.", "تظهر الآراء الجديدة هنا في انتظار قرارك."),
  reviewSubmitted: l("Envoyé le", "Submitted", "تاريخ الإرسال"),
  reviewRating: l("étoiles sur 5", "out of 5 stars", "نجوم من 5"),
  welcome: l(
    "Tout commence par le goût.",
    "It all starts with good taste.",
    "كل شيء يبدأ بالمذاق.",
  ),
  intro: l(
    "Votre carte, vos adresses, votre signature. Tout se gère ici.",
    "Your menu, your places, your signature. Manage it all here.",
    "قائمتك، فروعك، بصمتك. إدارة كل شيء من هنا.",
  ),
  website: l("Voir le site", "View website", "عرض الموقع"),
  logout: l("Déconnexion", "Sign out", "تسجيل الخروج"),
  login: l(
    "Bienvenue en cuisine.",
    "Welcome behind the counter.",
    "مرحباً بك خلف الكواليس.",
  ),
  loginSub: l(
    "Connectez-vous pour gérer Lma3louma.",
    "Sign in to manage Lma3louma.",
    "سجّل الدخول لإدارة المعلومة.",
  ),
  email: l("Adresse e-mail", "Email address", "البريد الإلكتروني"),
  password: l("Mot de passe", "Password", "كلمة المرور"),
  signin: l("Se connecter", "Sign in", "تسجيل الدخول"),
  denied: l(
    "Ce compte n’a pas accès à l’administration.",
    "This account does not have admin access.",
    "هذا الحساب ليس لديه صلاحية الإدارة.",
  ),
  loginError: l(
    "Connexion impossible. Vérifiez vos identifiants et réessayez.",
    "Unable to sign in. Check your credentials and try again.",
    "تعذّر الدخول. تحقق من بياناتك وحاول مجدداً.",
  ),
  private: l(
    "Espace réservé à l’équipe Lma3louma",
    "For the Lma3louma team",
    "خاص بفريق المعلومة",
  ),
  setup: l(
    "Connexion Supabase à finaliser",
    "Supabase connection needed",
    "يلزم ربط Supabase",
  ),
  setupSub: l(
    "Le tableau de bord sera disponible une fois le projet Supabase configuré. Consultez le guide de configuration du projet.",
    "The dashboard will be available once the Supabase project is configured. See the project setup guide.",
    "ستتوفر لوحة التحكم بعد إعداد مشروع Supabase. راجع دليل إعداد المشروع.",
  ),
  loading: l("Chargement…", "Loading…", "جارٍ التحميل…"),
  search: l("Rechercher…", "Search…", "بحث…"),
  add: l("Ajouter", "Add", "إضافة"),
  edit: l("Modifier", "Edit", "تعديل"),
  delete: l("Supprimer", "Delete", "حذف"),
  save: l("Enregistrer", "Save changes", "حفظ التغييرات"),
  cancel: l("Annuler", "Cancel", "إلغاء"),
  saving: l("Enregistrement…", "Saving…", "جارٍ الحفظ…"),
  saved: l(
    "Modifications enregistrées.",
    "Changes saved.",
    "تم حفظ التغييرات.",
  ),
  deleted: l("Élément supprimé.", "Item deleted.", "تم حذف العنصر."),
  error: l(
    "L’opération a échoué. Vérifiez votre connexion et vos droits d’accès, puis réessayez.",
    "The operation failed. Check your connection and access, then try again.",
    "فشلت العملية. تحقق من الاتصال والصلاحيات وحاول مجدداً.",
  ),
  loadError: l(
    "Impossible de charger les données. Réessayez.",
    "Could not load the data. Please retry.",
    "تعذّر تحميل البيانات. حاول مجدداً.",
  ),
  retry: l("Réessayer", "Retry", "إعادة المحاولة"),
  all: l("Toutes les catégories", "All categories", "جميع الفئات"),
  allStatus: l("Tous les statuts", "All statuses", "جميع الحالات"),
  published: l("Visible", "Published", "ظاهر"),
  hidden: l("Masqué", "Hidden", "مخفي"),
  status: l("Visibilité", "Visibility", "الظهور"),
  name: l("Nom", "Name", "الاسم"),
  description: l("Description", "Description", "الوصف"),
  price: l("Prix (DH)", "Price (DH)", "السعر (درهم)"),
  menuPrice: l(
    "Prix en menu (DH) · facultatif",
    "Meal price (DH) · optional",
    "سعر الوجبة (درهم) · اختياري",
  ),
  category: l("Catégorie", "Category", "الفئة"),
  image: l("Photo", "Photo", "الصورة"),
  imageUrl: l("URL de l’image", "Image URL", "رابط الصورة"),
  custom: l("Image personnalisée", "Custom image", "صورة مخصصة"),
  icon: l("Symbole", "Symbol", "الرمز"),
  order: l("Ordre d’affichage", "Display order", "ترتيب العرض"),
  area: l("Sous-titre du quartier", "Area subtitle", "وصف الحي"),
  address: l("Adresse", "Address", "العنوان"),
  map: l("Lien Google Maps", "Google Maps link", "رابط خرائط Google"),
  tag: l("Badge", "Badge", "الشارة"),
  none: l("Aucun", "None", "بدون"),
  signature: l("Signature", "Signature", "مميز"),
  spicy: l("Épicé", "Spicy", "حار"),
  sharing: l("À partager", "To share", "للمشاركة"),
  variants: l("Variantes", "Variants", "الخيارات"),
  addVariant: l("Ajouter une variante", "Add variant", "إضافة خيار"),
  empty: l(
    "Rien ici pour le moment.",
    "Nothing here yet.",
    "لا توجد عناصر بعد.",
  ),
  emptySub: l(
    "Ajoutez un élément ou ajustez vos filtres.",
    "Add an entry or adjust your filters.",
    "أضف عنصراً أو عدّل خيارات البحث.",
  ),
  deleteTitle: l(
    "Supprimer cet élément ?",
    "Delete this entry?",
    "حذف هذا العنصر؟",
  ),
  deleteSub: l(
    "Cette suppression est définitive et sera répercutée sur le site.",
    "This deletion is permanent and will update the website.",
    "هذا الحذف نهائي وسيتم تطبيقه على الموقع.",
  ),
  categoryInUse: l(
    "Déplacez ou supprimez d’abord les plats de cette catégorie.",
    "Move or delete the dishes in this category first.",
    "انقل أو احذف أطباق هذه الفئة أولاً.",
  ),
  noCategory: l(
    "Ajoutez d’abord une catégorie pour créer un plat.",
    "Add a category before creating a dish.",
    "أضف فئة أولاً لإنشاء طبق.",
  ),
  live: l("Contenu du site", "Website content", "محتوى الموقع"),
  quick: l("À vous de jouer", "Make it yours", "لمستك الخاصة"),
  quickSub: l(
    "Un nouveau plat ? Une nouvelle adresse ? Mettez votre site à jour en quelques clics.",
    "A new dish? A new location? Update your website in a few clicks.",
    "طبق جديد؟ فرع جديد؟ حدّث موقعك ببضع نقرات.",
  ),
  recent: l(
    "La carte en un coup d’œil",
    "Your menu at a glance",
    "نظرة على قائمتك",
  ),
  manage: l("Gérer la carte", "Manage menu", "إدارة القائمة"),
  visibleHelp: l(
    "Les éléments visibles apparaissent sur le site. Masquer une catégorie masque aussi ses plats.",
    "Published entries appear on the website. Hiding a category also hides its dishes.",
    "تظهر العناصر المنشورة على الموقع. إخفاء فئة يخفي أطباقها أيضاً.",
  ),
  translations: l(
    "Contenu en trois langues",
    "Content in three languages",
    "المحتوى بثلاث لغات",
  ),
  imageHelp: l(
    "Utilisez une URL HTTPS ou un chemin /assets/.",
    "Use an HTTPS URL or an /assets/ path.",
    "استخدم رابط HTTPS أو مسار /assets/.",
  ),
  upload: l("Téléverser une photo", "Upload a photo", "رفع صورة"),
  uploading: l("Téléversement…", "Uploading…", "جارٍ الرفع…"),
  uploadHelp: l(
    "JPEG, PNG, WebP ou AVIF · 5 Mo maximum.",
    "JPEG, PNG, WebP or AVIF · 5 MB maximum.",
    "JPEG أو PNG أو WebP أو AVIF · 5 ميغابايت كحد أقصى.",
  ),
  uploadOr: l("ou collez une URL", "or paste a URL", "أو الصق رابطاً"),
  uploaded: l("Photo téléversée.", "Photo uploaded.", "تم رفع الصورة."),
  uploadError: l(
    "Le téléversement a échoué. Réessayez.",
    "Upload failed. Please try again.",
    "فشل رفع الصورة. حاول مرة أخرى.",
  ),
  imageType: l(
    "Format non pris en charge. Utilisez JPEG, PNG, WebP ou AVIF.",
    "Unsupported format. Use JPEG, PNG, WebP or AVIF.",
    "صيغة غير مدعومة. استخدم JPEG أو PNG أو WebP أو AVIF.",
  ),
  imageSize: l(
    "Image trop lourde. 5 Mo maximum.",
    "Image too large. 5 MB maximum.",
    "الصورة كبيرة جداً. 5 ميغابايت كحد أقصى.",
  ),
};
export type CopyKey = keyof typeof copy;
