import { l } from "../data";
export const copy = {
  dashboard: l("Tableau de bord", "Dashboard", "لوحة التحكم"),
  overview: l("Vue d’ensemble", "Overview", "نظرة عامة"),
  menu: l("Carte & plats", "Menu & dishes", "القائمة والأطباق"),
  categories: l("Catégories", "Categories", "الفئات"),
  locations: l("Restaurants", "Locations", "الفروع"),
  reviews: l("Avis clients", "Customer reviews", "آراء الزبائن"),
  reviewsHelp: l(
    "Vérifiez les avis et leurs photos avant publication. Seuls les avis approuvés apparaissent sur le site.",
    "Check reviews and photos before publishing. Only approved reviews appear on the website.",
    "راجع الآراء والصور قبل النشر. تظهر الآراء المعتمدة فقط على الموقع.",
  ),
  reviewsPending: l("En attente", "Pending", "قيد المراجعة"),
  reviewsApproved: l("Approuvés", "Approved", "معتمدة"),
  reviewsRejected: l("Refusés", "Rejected", "مرفوضة"),
  reviewsFilter: l("Filtrer les avis", "Filter reviews", "تصفية الآراء"),
  reviewsSearch: l("Rechercher un avis…", "Search reviews…", "البحث في الآراء…"),
  reviewsRefresh: l("Actualiser les avis", "Refresh reviews", "تحديث الآراء"),
  reviewsApprove: l("Approuver", "Approve", "اعتماد"),
  reviewsReject: l("Refuser", "Reject", "رفض"),
  reviewApproved: l("Avis approuvé et publié.", "Review approved and published.", "تم اعتماد الرأي ونشره."),
  reviewRejected: l("Avis refusé et masqué du site.", "Review rejected and hidden from the website.", "تم رفض الرأي وإخفاؤه من الموقع."),
  reviewsEmpty: l("Aucun avis dans cette sélection.", "No reviews in this selection.", "لا توجد آراء ضمن هذا الاختيار."),
  reviewsEmptyHelp: l("Les nouveaux avis arrivent ici en attente de votre décision.", "New reviews appear here while awaiting your decision.", "تظهر الآراء الجديدة هنا في انتظار قرارك."),
  reviewSubmitted: l("Envoyé le", "Submitted", "تاريخ الإرسال"),
  reviewRating: l("étoiles sur 5", "out of 5 stars", "نجوم من 5"),
  welcome: l(
    "Tout commence par le goût.",
    "It all starts with good taste.",
    "كل شيء يبدأ بالمذاق.",
  ),
  intro: l(
    "Votre carte, vos adresses, votre signature. Tout se gère ici.",
    "Your menu, your places, your signature. Manage it all here.",
    "قائمتك، فروعك، بصمتك. إدارة كل شيء من هنا.",
  ),
  website: l("Voir le site", "View website", "عرض الموقع"),
  logout: l("Déconnexion", "Sign out", "تسجيل الخروج"),
  login: l(
    "Bienvenue en cuisine.",
    "Welcome behind the counter.",
    "مرحباً بك خلف الكواليس.",
  ),
  loginSub: l(
    "Connectez-vous pour gérer Lma3louma.",
    "Sign in to manage Lma3louma.",
    "سجّل الدخول لإدارة المعلومة.",
  ),
  email: l("Adresse e-mail", "Email address", "البريد الإلكتروني"),
  password: l("Mot de passe", "Password", "كلمة المرور"),
  signin: l("Se connecter", "Sign in", "تسجيل الدخول"),
  denied: l(
    "Ce compte n’a pas accès à l’administration.",
    "This account does not have admin access.",
    "هذا الحساب ليس لديه صلاحية الإدارة.",
  ),
  loginError: l(
    "Connexion impossible. Vérifiez vos identifiants et réessayez.",
    "Unable to sign in. Check your credentials and try again.",
    "تعذّر الدخول. تحقق من بياناتك وحاول مجدداً.",
  ),
  private: l(
    "Espace réservé à l’équipe Lma3louma",
    "For the Lma3louma team",
    "خاص بفريق المعلومة",
  ),
  setup: l(
    "Connexion Supabase à finaliser",
    "Supabase connection needed",
    "يلزم ربط Supabase",
  ),
  setupSub: l(
    "Le tableau de bord sera disponible une fois le projet Supabase configuré. Consultez le guide de configuration du projet.",
    "The dashboard will be available once the Supabase project is configured. See the project setup guide.",
    "ستتوفر لوحة التحكم بعد إعداد مشروع Supabase. راجع دليل إعداد المشروع.",
  ),
  loading: l("Chargement…", "Loading…", "جارٍ التحميل…"),
  search: l("Rechercher…", "Search…", "بحث…"),
  add: l("Ajouter", "Add", "إضافة"),
  edit: l("Modifier", "Edit", "تعديل"),
  delete: l("Supprimer", "Delete", "حذف"),
  save: l("Enregistrer", "Save changes", "حفظ التغييرات"),
  cancel: l("Annuler", "Cancel", "إلغاء"),
  saving: l("Enregistrement…", "Saving…", "جارٍ الحفظ…"),
  saved: l(
    "Modifications enregistrées.",
    "Changes saved.",
    "تم حفظ التغييرات.",
  ),
  deleted: l("Élément supprimé.", "Item deleted.", "تم حذف العنصر."),
  error: l(
    "L’opération a échoué. Vérifiez votre connexion et vos droits d’accès, puis réessayez.",
    "The operation failed. Check your connection and access, then try again.",
    "فشلت العملية. تحقق من الاتصال والصلاحيات وحاول مجدداً.",
  ),
  loadError: l(
    "Impossible de charger les données. Réessayez.",
    "Could not load the data. Please retry.",
    "تعذّر تحميل البيانات. حاول مجدداً.",
  ),
  retry: l("Réessayer", "Retry", "إعادة المحاولة"),
  all: l("Toutes les catégories", "All categories", "جميع الفئات"),
  allStatus: l("Tous les statuts", "All statuses", "جميع الحالات"),
  published: l("Visible", "Published", "ظاهر"),
  hidden: l("Masqué", "Hidden", "مخفي"),
  status: l("Visibilité", "Visibility", "الظهور"),
  name: l("Nom", "Name", "الاسم"),
  description: l("Description", "Description", "الوصف"),
  price: l("Prix (DH)", "Price (DH)", "السعر (درهم)"),
  menuPrice: l(
    "Prix en menu (DH) · facultatif",
    "Meal price (DH) · optional",
    "سعر الوجبة (درهم) · اختياري",
  ),
  category: l("Catégorie", "Category", "الفئة"),
  image: l("Photo", "Photo", "الصورة"),
  imageUrl: l("URL de l’image", "Image URL", "رابط الصورة"),
  custom: l("Image personnalisée", "Custom image", "صورة مخصصة"),
  icon: l("Symbole", "Symbol", "الرمز"),
  order: l("Ordre d’affichage", "Display order", "ترتيب العرض"),
  area: l("Sous-titre du quartier", "Area subtitle", "وصف الحي"),
  address: l("Adresse", "Address", "العنوان"),
  map: l("Lien Google Maps", "Google Maps link", "رابط خرائط Google"),
  tag: l("Badge", "Badge", "الشارة"),
  none: l("Aucun", "None", "بدون"),
  signature: l("Signature", "Signature", "مميز"),
  spicy: l("Épicé", "Spicy", "حار"),
  sharing: l("À partager", "To share", "للمشاركة"),
  variants: l("Variantes", "Variants", "الخيارات"),
  addVariant: l("Ajouter une variante", "Add variant", "إضافة خيار"),
  empty: l(
    "Rien ici pour le moment.",
    "Nothing here yet.",
    "لا توجد عناصر بعد.",
  ),
  emptySub: l(
    "Ajoutez un élément ou ajustez vos filtres.",
    "Add an entry or adjust your filters.",
    "أضف عنصراً أو عدّل خيارات البحث.",
  ),
  deleteTitle: l(
    "Supprimer cet élément ?",
    "Delete this entry?",
    "حذف هذا العنصر؟",
  ),
  deleteSub: l(
    "Cette suppression est définitive et sera répercutée sur le site.",
    "This deletion is permanent and will update the website.",
    "هذا الحذف نهائي وسيتم تطبيقه على الموقع.",
  ),
  categoryInUse: l(
    "Déplacez ou supprimez d’abord les plats de cette catégorie.",
    "Move or delete the dishes in this category first.",
    "انقل أو احذف أطباق هذه الفئة أولاً.",
  ),
  noCategory: l(
    "Ajoutez d’abord une catégorie pour créer un plat.",
    "Add a category before creating a dish.",
    "أضف فئة أولاً لإنشاء طبق.",
  ),
  live: l("Contenu du site", "Website content", "محتوى الموقع"),
  quick: l("À vous de jouer", "Make it yours", "لمستك الخاصة"),
  quickSub: l(
    "Un nouveau plat ? Une nouvelle adresse ? Mettez votre site à jour en quelques clics.",
    "A new dish? A new location? Update your website in a few clicks.",
    "طبق جديد؟ فرع جديد؟ حدّث موقعك ببضع نقرات.",
  ),
  recent: l(
    "La carte en un coup d’œil",
    "Your menu at a glance",
    "نظرة على قائمتك",
  ),
  manage: l("Gérer la carte", "Manage menu", "إدارة القائمة"),
  visibleHelp: l(
    "Les éléments visibles apparaissent sur le site. Masquer une catégorie masque aussi ses plats.",
    "Published entries appear on the website. Hiding a category also hides its dishes.",
    "تظهر العناصر المنشورة على الموقع. إخفاء فئة يخفي أطباقها أيضاً.",
  ),
  translations: l(
    "Contenu en trois langues",
    "Content in three languages",
    "المحتوى بثلاث لغات",
  ),
  imageHelp: l(
    "Utilisez une URL HTTPS ou un chemin /assets/.",
    "Use an HTTPS URL or an /assets/ path.",
    "استخدم رابط HTTPS أو مسار /assets/.",
  ),
  upload: l("Téléverser une photo", "Upload a photo", "رفع صورة"),
  uploading: l("Téléversement…", "Uploading…", "جارٍ الرفع…"),
  uploadHelp: l(
    "JPEG, PNG, WebP ou AVIF · 5 Mo maximum.",
    "JPEG, PNG, WebP or AVIF · 5 MB maximum.",
    "JPEG أو PNG أو WebP أو AVIF · 5 ميغابايت كحد أقصى.",
  ),
  uploadOr: l("ou collez une URL", "or paste a URL", "أو الصق رابطاً"),
  uploaded: l("Photo téléversée.", "Photo uploaded.", "تم رفع الصورة."),
  uploadError: l(
    "Le téléversement a échoué. Réessayez.",
    "Upload failed. Please try again.",
    "فشل رفع الصورة. حاول مرة أخرى.",
  ),
  imageType: l(
    "Format non pris en charge. Utilisez JPEG, PNG, WebP ou AVIF.",
    "Unsupported format. Use JPEG, PNG, WebP or AVIF.",
    "صيغة غير مدعومة. استخدم JPEG أو PNG أو WebP أو AVIF.",
  ),
  imageSize: l(
    "Image trop lourde. 5 Mo maximum.",
    "Image too large. 5 MB maximum.",
    "الصورة كبيرة جداً. 5 ميغابايت كحد أقصى.",
  ),
};
export type CopyKey = keyof typeof copy;
