-- Guests submit immutable content; only existing admins can moderate it.
-- IDs are generated by the browser before its optional photo upload.
create table public.reviews (
  id uuid primary key,
  title text not null
    check (title = btrim(title, E' \t\n\r\f') and char_length(title) between 3 and 100),
  description text not null
    check (description = btrim(description, E' \t\n\r\f') and char_length(description) between 10 and 1500),
  rating smallint not null check (rating between 1 and 5),
  image_path text unique
    check (image_path is null or image_path in (
      id::text || '/photo.jpg',
      id::text || '/photo.png',
      id::text || '/photo.webp'
    )),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  check (
    (status = 'pending' and moderated_at is null)
    or (status in ('approved', 'rejected') and moderated_at is not null)
  )
);

create index reviews_status_created_at_idx on public.reviews(status, created_at desc);

-- The trigger owns the timestamp, without elevated privileges or client input.
create function public.set_review_moderated_at() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin
  new.moderated_at := case when new.status = 'pending' then null else statement_timestamp() end;
  return new;
end;
$$;
revoke all on function public.set_review_moderated_at() from public, anon, authenticated;

create trigger reviews_set_moderated_at
  before update of status on public.reviews
  for each row when (old.status is distinct from new.status)
  execute function public.set_review_moderated_at();

alter table public.reviews enable row level security;
revoke all on public.reviews from anon, authenticated;
grant select on public.reviews to anon, authenticated;
grant insert (id, title, description, rating, image_path) on public.reviews to anon, authenticated;
grant update (status) on public.reviews to authenticated;

-- A pending row is intentionally unreadable to its guest submitter. Clients
-- must INSERT without SELECT/RETURNING, then show the moderation receipt.
create policy "Guests submit pending reviews" on public.reviews
  for insert to anon, authenticated
  with check (status = 'pending' and moderated_at is null);

create policy "Public reads approved reviews" on public.reviews
  for select to anon, authenticated
  using (status = 'approved');

-- Keep membership checks in authenticated-only policies. The anonymous role
-- must never need SELECT permission on the private admin membership table.
create policy "Admins read all reviews" on public.reviews
  for select to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

create policy "Admins moderate reviews" on public.reviews
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
